# Use jammy on local arm64/Apple Silicon, otherwise, use focal
FROM buildpack-deps:jammy-curl

LABEL dev.containers.features="common"

ENV LANG="C.UTF-8"

# Set the SHELL environment variable to /bin/bash
ENV SHELL /bin/bash
