version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - /var/run/docker.sock:/var/run/docker-host.sock
      - ..:/workspace:cached
     # - springboard-dev-bashhistory:/commandhistory

    entrypoint: /usr/local/share/docker-init.sh
    command: sleep infinity
    network_mode: service:db

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postges
      POSTGRES_PASSWORD: postgres1234

    # Uncomment the next line to use a non-root user for all processes.

volumes:
  springboard-dev-bashhistory:
  postgres-data:

