name: Prebuild Dev Container

on:
  push:
    branches:
      - main
  pull_request:

  env:
    REGISTRY: ghcr.io

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  build:
    name: Build Springboard-Dev Container
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [armhf, armv7, aarch64, amd64, i386]
        
    steps:
    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v4
      
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Build Dev Container Image
      if: github.event.pull_request.head.repo.full_name != github.repository
      with:
        args: |          --image ${{ github.repository}}--{arch} \
          --self-cache \
          --version $GITHUB_REF_SLUG \
          --no-latest \
      working-directory: .devcontainer/

    - name: Log in to Docker Hub (or your preferred registry)
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push Dev Container Image
      run: |
        # Push the image to your container registry
        docker push my-dev-container:latest
      working-directory: .devcontainer/

