name: Prebuild Dev Container

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Build Dev Container Image
      run: |
        # Add your custom build commands here
        # For example, if you are using Docker to build the image:
        docker build -t my-dev-container:latest .
      working-directory: .devcontainer/

    - name: Log in to Docker Hub (or your preferred registry)
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Dev Container Image
      run: |
        # Push the image to your container registry
        docker push my-dev-container:latest
      working-directory: .devcontainer/

